### ISSUE TITLE
.bower.json contains illegal json

### ISSUE THREAD

**Issue by joelharkes** [flesler/jquery.serialScroll#14] opened 2015-11-30 11:16 UTC
installing package with bower i get 2 bower.json files: bower.json and .bower.json.

the .bower.json file contains:

```javascript
{
  "name": "jquery.serialscroll",
  "version": "1.3.1",
  "description": "Animated scrolling of series with jQuery",
  "homepage": "https://github.com/flesler/jquery.serialScroll",
  "main": [
    "./jquery.serialScroll.js",
    "./jquery.serialScroll.min.js"
  ],
  "dependencies": {
    "jquery": ">=1.8",
    "jquery.scrollTo": ">=2.1.0"
  },
  "keywords": [
    "slideshow",
    "sequence",
    "animated",
    "animation",
    "scrolling",
    "scroll",
    "prev",
    "next"
  ],
  "author": {
    "name": "Ariel Flesler",
    "web": "http://flesler.blogspot.com/"
  },
  "_release": "1.3.1",
  "_resolution": {
    "type": "version",
    "tag": "1.3.1",
    "commit": "eb3c573bee7f0fa60c46c31822f03c2479eb6b6e"
  },
  "_source": "git://github.com/flesler/jquery.serialScroll.git",
  "_target": "*",
  "_originalSource": "jquery.serialScroll"
}ll"
}
```

the }ll" on the second last row is incorrect json and kills bower install sometimes

**Comment by joelharkes** [comment] 2015-11-30 11:19
possibly a bower problem instead?

**Comment by flesler** [comment] 2015-12-02 13:56
Hi,

The bower.json is similar in structure to [jquery.scrollTo's](https://github.com/flesler/jquery.scrollTo/blob/master/bower.json) and no one complained about that one even though the plugin is widely used.

I think something wrong on your side, though I'm not 100% sure.
I'll close this, do reopen if you find out the cause and it's due to something wrong in this bower.json file

**Closed by flesler** 2015-12-02 13:56 UTC
